title: "www.biskupcova42.cz"
email: "vybor@biskupcova42.cz"
#logo: /assets/img/logo.png
description: >
  Společensví vlastníků Biskupcova 42, Praha 3 je právnická osoba založená 1. 7. 2000 k ochraně zájmů spoluvlastníků, 
  tedy zajištění péče o spoluvlastnické podíly.
show_downloads: true
show_excerpts: true
#google_analytics:

markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

list_title: "Aktuality"

minima:
  date_format: "%d. %m. %Y"

github_username: "26442566"
keybase: lefak
rss: rss
